<template>
  <LearnecAppShell role="ADMIN">
    <section data-review-center class="review-center">
      <header><div><p>教学闭环 / 批阅中心</p><h1>提交证据审查</h1></div><select v-model="status" @change="loadQueue"><option value="SUBMITTED">待批阅</option><option value="GRADED">已批阅</option><option value="RETURNED">已退回</option></select></header>
      <div class="review-grid">
        <aside data-review-queue><h2>学生提交</h2><button v-for="item in queue" :key="item.studentTaskId" :class="{selected:item.studentTaskId===selectedId}" @click="select(item.studentTaskId)"><strong>{{ item.student.displayName }}</strong><span>{{ item.title }}</span><small>{{ item.status }} · {{ item.autoScore }} 自动分</small></button><p v-if="!queue.length">暂无符合条件的提交。</p></aside>
        <main data-review-evidence><template v-if="detail"><h2>作品与证据</h2><p class="meta">{{ detail.student.displayName }} · 第 {{ detail.submission.currentVersion }} 次提交</p><article v-for="part in detail.submission.current.parts" :key="part.id"><strong>{{ part.sectionId }}</strong><pre>{{ JSON.stringify(part.answer, null, 2) }}</pre></article><h3>操作时间线</h3><ol><li v-for="event in detail.evidence.events" :key="event.id">{{ event.eventType }} <small>{{ date(event.createdAt) }}</small></li></ol></template><p v-else>从左侧选择一份提交以查看证据。</p></main>
        <aside data-review-grading><template v-if="detail"><h2>综合评分</h2><dl><dt>自动分（{{ detail.grading.autoWeight }}%）</dt><dd>{{ detail.grading.autoScore }}</dd><dt>人工分（{{ detail.grading.manualWeight }}%）</dt><dd><input v-model.number="manualScore" type="number" min="0" max="100"></dd></dl><label>评语<textarea v-model="feedback" maxlength="2000" /></label><p v-if="message" class="message">{{ message }}</p><div class="actions"><button class="primary" :disabled="saving" @click="grade">保存评分</button><button :disabled="saving" @click="returnTask">退回重做</button></div><h3>评分修订</h3><ol><li v-for="revision in detail.grading.grade?.revisions ?? []" :key="revision.revision">第 {{ revision.revision }} 次：{{ revision.score }} 分</li></ol></template><p v-else>评分项会随提交证据显示。</p></aside>
      </div>
    </section>
  </LearnecAppShell>
</template>
<script setup lang="ts">
type Queue={studentTaskId:string;student:{displayName:string};title:string;status:string;autoScore:number}; const ssrHeaders=import.meta.server?useRequestHeaders(['cookie']):undefined; const status=ref('SUBMITTED'); const queue=ref<Queue[]>([]); const selectedId=ref(''); const detail=ref<any>(null); const manualScore=ref(0); const feedback=ref(''); const saving=ref(false); const message=ref('');
const date=(value:string)=>new Date(value).toLocaleString('zh-CN');
async function loadQueue(){const result=await $fetch<{items:Queue[]}>(`/api/admin/reviews?status=${status.value}`,{headers:ssrHeaders});queue.value=result.items;if(!queue.value.some(item=>item.studentTaskId===selectedId.value)){selectedId.value=queue.value[0]?.studentTaskId??'';if(selectedId.value)await select(selectedId.value)}}
async function select(id:string){selectedId.value=id;detail.value=await $fetch(`/api/admin/reviews/${id}`,{headers:ssrHeaders});manualScore.value=detail.value.grading.grade?.manualScore??0;feedback.value=detail.value.grading.grade?.feedback??'';message.value=''}
async function mutate(action:'grade'|'return'){if(!detail.value)return;saving.value=true;message.value='';try{const result:any=await $fetch(`/api/admin/reviews/${selectedId.value}/${action}`,{method:'POST',headers:useCsrfHeaders(),body:{manualScore:manualScore.value,feedback:feedback.value,expectedVersion:detail.value.submission.currentVersion}});message.value=action==='grade'?`已保存，总分 ${result.grade.score}`:'已退回学生重做';await loadQueue();if(action==='grade')await select(selectedId.value);else detail.value=null}catch{message.value='操作未保存，请检查评分、评语和提交版本。'}finally{saving.value=false}}
const grade=()=>mutate('grade');const returnTask=()=>mutate('return');await loadQueue();
</script>
<style scoped>.review-center header{display:flex;align-items:end;justify-content:space-between;margin-bottom:18px}.review-center p{margin:0;color:#1677ff;font-weight:700;font-size:13px}.review-center h1{margin:7px 0 0;font-size:28px}.review-center select,input,textarea{border:1px solid #d0d5dd;border-radius:5px;padding:9px;font:inherit}.review-grid{display:grid;grid-template-columns:minmax(190px,.8fr) minmax(320px,1.5fr) minmax(230px,.9fr);min-height:620px;border:1px solid #e4e8ef;background:#fff}.review-grid>*,.review-grid aside{padding:18px;min-width:0}.review-grid>aside{border-right:1px solid #e4e8ef}.review-grid>aside:last-child{border-right:0;border-left:1px solid #e4e8ef}.review-grid h2{margin:0 0 14px;font-size:17px}.review-grid button{display:block;width:100%;padding:10px;margin:0 0 8px;border:1px solid #e4e8ef;border-radius:5px;background:#fff;text-align:left}.review-grid button.selected{border-color:#1677ff;background:#eff8ff}.review-grid button span,.review-grid button small{display:block;margin-top:4px;color:#667085}.review-grid pre{max-height:180px;overflow:auto;padding:10px;background:#f7f9fc;font-size:12px}.meta,small{color:#667085}.review-grid label{display:grid;gap:6px;font-size:13px}.review-grid textarea{min-height:110px;resize:vertical}.review-grid dl{display:grid;grid-template-columns:1fr auto;gap:12px}.review-grid dt,.review-grid dd{margin:0}.actions{display:flex;gap:8px;margin:16px 0}.actions .primary{background:#1677ff;color:#fff;border-color:#1677ff;text-align:center}.message{margin:8px 0!important;color:#1677ff!important}@media(max-width:900px){.review-grid{grid-template-columns:1fr}.review-grid>aside,.review-grid>aside:last-child{border:0;border-bottom:1px solid #e4e8ef}.review-grid>aside:last-child{border-bottom:0}}</style>
