<template><LearnecAppShell role="ADMIN"><section class="centers" data-training-centers><header><div><p>工作中心快捷入口</p><h1>公共实训中心</h1><span>按教学、比赛和考证分类管理实训室；未开放引擎仅展示真实能力状态。</span></div><NuxtLink to="/admin">返回工作中心</NuxtLink></header><p v-if="loading" class="state">正在读取实训室…</p><p v-else-if="error" class="error" role="alert">{{ error }}</p><div v-else class="center-grid"><article v-for="center in centers" :key="center.type" data-training-center-type :data-center-type="center.type"><div><span :class="center.capabilityStatus==='AVAILABLE'?'available':'soon'">{{ center.capabilityStatus==='AVAILABLE'?'可用':'规划中' }}</span><h2>{{ labels[center.type].title }}</h2><p>{{ labels[center.type].description }}</p></div><dl><div><dt>当前实训室</dt><dd>{{ center.rooms.length }}</dd></div><div><dt>能力状态</dt><dd>{{ center.capabilityStatus }}</dd></div></dl><ul v-if="center.rooms.length"><li v-for="room in center.rooms" :key="room.id">{{ room.name }}</li></ul><p v-else class="empty">暂无该类型实训室记录。</p></article></div></section></LearnecAppShell></template>
<script setup lang="ts">
interface Center{type:'TEACHING'|'COMPETITION'|'CERTIFICATION';capabilityStatus:string;rooms:Array<{id:string;name:string}>}
const centers=ref<Center[]>([]),loading=ref(true),error=ref('');const labels={TEACHING:{title:'教学实训室',description:'用于日常组课、工单发布和学生实训。'},COMPETITION:{title:'比赛实训室',description:'预留赛前训练、比赛时间及个人/团队配置入口。'},CERTIFICATION:{title:'考证实训室',description:'预留考证训练、模拟考试和考期配置入口。'}}
onMounted(async()=>{try{centers.value=(await $fetch<{centers:Center[]}>('/api/admin/training-centers')).centers}catch{error.value='实训中心读取失败，请稍后重试。'}finally{loading.value=false}})
</script>
<style scoped>
.centers{display:grid;gap:24px}.centers>header{display:flex;justify-content:space-between;gap:18px}.centers header p{margin:0 0 6px;color:#145bc2;font-size:12px;font-weight:700}.centers h1{margin:0 0 8px;font-size:26px}.centers header span{color:#667085}.centers header a{height:36px;padding:0 12px;border:1px solid #cbd5e1;border-radius:5px;color:#145bc2;text-decoration:none;display:flex;align-items:center}.center-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid #e4e8ef;border-left:1px solid #e4e8ef;background:#fff}.center-grid article{display:grid;align-content:start;gap:18px;min-height:310px;padding:22px;border-right:1px solid #e4e8ef;border-bottom:1px solid #e4e8ef}.center-grid span{display:inline-block;font-size:12px;font-weight:700}.available{color:#067647}.soon{color:#b54708}.center-grid h2{margin:8px 0;font-size:20px}.center-grid p{margin:0;color:#667085;line-height:1.6}.center-grid dl{display:grid;grid-template-columns:1fr 1fr;margin:0;padding-block:14px;border-block:1px solid #eaecf0}.center-grid dt{color:#667085;font-size:11px}.center-grid dd{margin:5px 0 0;font-weight:700}.center-grid ul{margin:0;padding-left:18px}.empty{font-size:13px}.state,.error{padding:16px;background:#fff;color:#667085}.error{background:#fef3f2;color:#b42318}@media(max-width:850px){.center-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.centers>header{flex-direction:column}.center-grid{grid-template-columns:1fr;border-left:0}}
</style>
