<template>
  <LearnecAppShell role="ADMIN"><section class="publication" data-work-order-publication>
    <header class="page-head"><div><p>实训任务管理 / 作业发布</p><h1>{{ task?.title || '发布工单' }}</h1><span>发布将冻结工单版本，并为班级中每名有效学生生成一条 StudentTask。</span></div><div class="actions"><NuxtLink :to="`/admin/tasks/${taskId}/edit`">返回编辑</NuxtLink><NuxtLink :to="`/admin/tasks/${taskId}/preview`">查看预览</NuxtLink></div></header>
    <p v-if="loading" class="state">正在读取发布信息…</p><p v-else-if="error" class="error" role="alert">{{ error }}</p>
    <template v-else-if="task&&publication"><section class="metrics"><div><span>工单状态</span><strong>{{ task.status==='PUBLISHED'?'已发布':'草稿' }}</strong></div><div><span>已生成学生任务</span><strong data-publication-count>{{ publication.taskCount }}</strong></div><div><span>发布版本</span><strong>v{{ task.assignmentVersion }}</strong></div></section>
      <form @submit.prevent="publish"><fieldset :disabled="publishing||task.status!=='DRAFT'"><legend>发布确认</legend><label>目标班级<select v-model="schedule.classId" required><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.name }}（{{ item.studentCount }} 人）</option></select></label><label>开放时间<input v-model="schedule.availableAt" type="datetime-local" /></label><label>截止时间<input v-model="schedule.dueAt" type="datetime-local" /></label><label class="check"><input v-model="schedule.lateAllowed" type="checkbox" /> 允许迟交</label><button type="submit" data-publish-work-order>{{ publishing?'正在发布…':'确认发布并生成学生任务' }}</button></fieldset></form>
      <p v-if="result" data-publication-result class="notice" role="status">已为 {{ result.taskCount }} 名学生生成任务，重复发布不会重复创建。</p>
      <section class="history"><h2>发布记录</h2><dl><div><dt>发布时间</dt><dd>{{ publication.publishedAt?formatDate(publication.publishedAt):'尚未发布' }}</dd></div><div v-for="(count,status) in publication.statusCounts" :key="status"><dt>{{ status }}</dt><dd>{{ count }}</dd></div></dl></section>
    </template>
  </section></LearnecAppShell>
</template>

<script setup lang="ts">
interface Task{id:string;classId:string;title:string;status:string;assignmentVersion:number;availableAt:string;dueAt:string|null;lateAllowed:boolean} interface AdminClass{id:string;name:string;studentCount:number} interface Publication{taskCount:number;publishedAt:string|null;statusCounts:Record<string,number>}
const taskId=String(useRoute().params.taskId),task=ref<Task|null>(null),classes=ref<AdminClass[]>([]),publication=ref<Publication|null>(null),loading=ref(true),publishing=ref(false),error=ref(''),result=ref<{taskCount:number}|null>(null)
const schedule=reactive({classId:'',availableAt:'',dueAt:'',lateAllowed:false})
function localDate(value:string|null){if(!value)return'';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function iso(value:string){return value?new Date(value).toISOString():null}
function formatDate(value:string){return new Date(value).toLocaleString('zh-CN',{hour12:false})}
async function load(){loading.value=true;error.value='';try{const[taskResponse,classResponse,publicationResponse]=await Promise.all([$fetch<{task:Task}>(`/api/admin/tasks/${taskId}`),$fetch<{classes:AdminClass[]}>('/api/admin/classes'),$fetch<{publication:Publication}>(`/api/admin/tasks/${taskId}/publications`)]);task.value=taskResponse.task;classes.value=classResponse.classes;publication.value=publicationResponse.publication;Object.assign(schedule,{classId:task.value.classId,availableAt:localDate(task.value.availableAt),dueAt:localDate(task.value.dueAt),lateAllowed:task.value.lateAllowed})}catch{error.value='发布信息读取失败，请返回工单列表重试。'}finally{loading.value=false}}
async function publish(){if(!task.value)return;publishing.value=true;error.value='';try{const response=await $fetch<{taskCount:number;assignment:{status:string}}>(`/api/admin/tasks/${taskId}/publish`,{method:'POST',headers:useCsrfHeaders({'Idempotency-Key':`publish-ui-${taskId}`}),body:{classId:schedule.classId,availableAt:iso(schedule.availableAt),dueAt:iso(schedule.dueAt),lateAllowed:schedule.lateAllowed}});result.value={taskCount:response.taskCount};task.value.status=response.assignment.status;publication.value=(await $fetch<{publication:Publication}>(`/api/admin/tasks/${taskId}/publications`)).publication}catch(caught){const code=(caught as{data?:{data?:{code?:string}}})?.data?.data?.code;error.value=code==='WORK_ORDER_WEIGHT_INVALID'?'评分权重或区块权重未达到 100%，请返回编辑器修正。':'发布失败，请检查时间、区块和班级权限。'}finally{publishing.value=false}}
onMounted(load)
</script>

<style scoped>
.publication{display:grid;gap:22px}.page-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.page-head p{margin:0 0 6px;color:#145bc2;font-size:12px;font-weight:700}.page-head h1{margin:0 0 8px;font-size:26px}.page-head span{color:#667085}.actions{display:flex;gap:8px}.actions a{padding:9px 12px;border:1px solid #cbd5e1;border-radius:5px;color:#145bc2;text-decoration:none;white-space:nowrap}.metrics{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #e4e8ef;background:#fff}.metrics div{display:grid;gap:6px;padding:16px;border-right:1px solid #e4e8ef}.metrics div:last-child{border:0}.metrics span{color:#667085;font-size:12px}.metrics strong{font-size:20px}fieldset{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:0;padding:22px;border:1px solid #e4e8ef;background:#fff}legend{padding:0 8px;font-weight:700}label{display:grid;gap:7px;color:#475467;font-size:13px}input,select{height:38px;box-sizing:border-box;padding:0 10px;border:1px solid #d0d5dd;border-radius:4px;background:#fff}.check{display:flex;align-items:center;gap:8px}.check input{width:auto}fieldset button{grid-column:1/-1;justify-self:start;min-height:40px;padding:0 16px;border:1px solid #1677ff;border-radius:4px;background:#1677ff;color:#fff;font-weight:700;cursor:pointer}fieldset:disabled button{opacity:.55}.history{padding-top:8px;border-top:1px solid #e4e8ef}.history h2{font-size:18px}.history dl{display:flex;flex-wrap:wrap;gap:12px}.history dl div{min-width:150px;padding:12px;background:#fff}.history dt{color:#667085;font-size:12px}.history dd{margin:6px 0 0;font-weight:700}.state,.error,.notice{padding:16px;background:#fff;color:#667085}.error{background:#fef3f2;color:#b42318}.notice{background:#ecfdf3;color:#067647}@media(max-width:760px){.page-head{flex-direction:column}.metrics,fieldset{grid-template-columns:1fr}.metrics div{border-right:0;border-bottom:1px solid #e4e8ef}.actions{flex-wrap:wrap}}
</style>
