ALTER TABLE "Grade"
  ADD COLUMN "autoScore" DECIMAL(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN "manualScore" DECIMAL(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN "autoWeight" DECIMAL(5,2) NOT NULL DEFAULT 70,
  ADD COLUMN "manualWeight" DECIMAL(5,2) NOT NULL DEFAULT 30;

ALTER TABLE "GradeRevision"
  ADD COLUMN "autoScore" DECIMAL(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN "manualScore" DECIMAL(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN "autoWeight" DECIMAL(5,2) NOT NULL DEFAULT 70,
  ADD COLUMN "manualWeight" DECIMAL(5,2) NOT NULL DEFAULT 30;
